# Generated by Django 4.0.3 on 2022-04-25 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=300)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other')], default='Male', max_length=10)),
                ('Height', models.FloatField()),
                ('BirthMark', models.CharField(max_length=100)),
                ('BodySize', models.CharField(max_length=10)),
                ('Date', models.DateField()),
                ('Mobile', models.IntegerField()),
                ('BodyColor', models.CharField(max_length=50)),
                ('ClothingColor', models.CharField(max_length=50)),
                ('FrontView', models.ImageField(upload_to='img')),
                ('LView', models.ImageField(upload_to='img')),
                ('RView', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='SearchCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Color', models.CharField(max_length=50, null=True)),
                ('Age', models.IntegerField(null=True)),
                ('Height', models.FloatField(null=True)),
                ('BodySize', models.CharField(max_length=10, null=True)),
                ('Mobile', models.IntegerField(null=True)),
                ('CloathingColor', models.CharField(max_length=50, null=True)),
                ('FrontView', models.ImageField(upload_to='img')),
                ('LView', models.ImageField(upload_to='img')),
                ('RView', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='img')),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.registercase')),
            ],
        ),
    ]
