# Generated by Django 4.0.5 on 2022-06-08 06:22

import case.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Color', models.CharField(max_length=50, null=True)),
                ('Age', models.IntegerField(null=True)),
                ('Height', models.FloatField(null=True)),
                ('BodySize', models.CharField(max_length=10, null=True)),
                ('Mobile', models.IntegerField(null=True)),
                ('CloathingColor', models.CharField(max_length=50, null=True)),
                ('FrontView', models.ImageField(upload_to=case.models.path_and_rename)),
                ('LView', models.ImageField(upload_to=case.models.path_and_rename)),
                ('RView', models.ImageField(upload_to=case.models.path_and_rename)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('NickName', models.CharField(max_length=100, null=True)),
                ('Address', models.CharField(max_length=300)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('Height', models.FloatField()),
                ('Weight', models.FloatField()),
                ('DOB', models.DateField()),
                ('BirthMark', models.CharField(max_length=100)),
                ('DOM', models.DateField()),
                ('Mobile', models.IntegerField()),
                ('ClothingColor', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to=case.models.path_and_rename)),
                ('Dis', models.CharField(max_length=100)),
                ('MissingPlace', models.CharField(max_length=100)),
                ('Status', models.BooleanField(default=False)),
                ('User_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
