# Generated by Django 4.0.3 on 2022-05-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercase',
            name='Gender',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
